'use client'

import { useState } from 'react'
import Image from 'next/image'

const WA = '5512992028120'
type Step = 1 | 2 | 3 | 4 | 5
type Quote = { service: string; category: string; model: string; situation: string; timing: string }

const services = ['Lavagem detalhada', 'Higienização interna', 'Polimento e cristalização', 'Proteção de pintura / cerâmica', 'Higienização de ar condicionado', 'Polimento e vitrificação de faróis']
const interiorSituations = ['Manutenção / limpeza normal', 'Manchas', 'Odor', 'Pelos de pet', 'Sujeira pesada', 'Outro / não sei']
const paintSituations = ['Perdeu brilho', 'Riscos leves', 'Manchas', 'Quero proteger', 'Preciso de avaliação']
const timings = ['Hoje / quanto antes', 'Esta semana', 'Próximos dias', 'Estou pesquisando']

function Arrow() { return <span aria-hidden="true">↗</span> }

export default function Home() {
  const [step, setStep] = useState<Step>(1)
  const [quote, setQuote] = useState<Quote>({ service: '', category: '', model: '', situation: '', timing: '' })
  const [menu, setMenu] = useState(false)
  const isPaint = quote.service.includes('Polimento') || quote.service.includes('Proteção')
  const situations = isPaint ? paintSituations : interiorSituations
  const startQuote = () => { document.getElementById('orcamento')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); setStep(1) }
  const choose = (key: keyof Quote, value: string, next?: Step) => { setQuote((q) => ({ ...q, [key]: value })); if (next) setStep(next) }
  const message = `Olá! Vim pelo orçamento online da Green Wash.\n\nServiço: ${quote.service}\nVeículo: ${quote.category}\nModelo: ${quote.model || 'A confirmar'}\nSituação: ${quote.situation}\nQuando: ${quote.timing}\n\nGostaria de saber valor e disponibilidade.`
  const whatsapp = `https://wa.me/${WA}?text=${encodeURIComponent(message)}`
  return <main>
    <a className="skip" href="#conteudo">Pular para o conteúdo</a>
    <header className="site-header"><a className="brand" href="#top" aria-label="Green Wash, início"><Image src="/projects/green-wash/brand/green-wash-logo.png" alt="Green Wash" width={270} height={96} /></a><nav className={menu ? 'nav open' : 'nav'} aria-label="Navegação principal"><a href="#servicos" onClick={() => setMenu(false)}>Serviços</a><a href="#diferenciais" onClick={() => setMenu(false)}>Por que Green Wash</a><a href="#orcamento" onClick={() => setMenu(false)}>Orçamento</a><a href="#localizacao" onClick={() => setMenu(false)}>Localização</a></nav><button className="header-cta" onClick={startQuote}>Pedir orçamento <Arrow /></button><button className="menu-button" aria-label={menu ? 'Fechar menu' : 'Abrir menu'} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? '×' : 'Menu'}</button></header>
    <div id="conteudo">
      <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><i /> Estética automotiva · Taubaté/SP</p><h1>Seu carro bem cuidado.<br /><em>Sem enrolação.</em></h1><p className="hero-text">Informe o que precisa uma vez. A Green Wash recebe tudo organizado para te responder melhor.</p><div className="hero-actions"><button className="button button-green" onClick={startQuote}>Montar meu orçamento <Arrow /></button><a className="text-link" href="#servicos">Conhecer serviços <span>↓</span></a></div></div><div className="hero-media"><Image src="/images/green-wash-team.png" alt="Equipe Green Wash realizando higienização automotiva" width={1200} height={1500} priority sizes="(max-width: 760px) 100vw, 45vw" /><div className="hero-caption"><span>Imagem real · equipe Green Wash</span><span>12+ anos no ramo</span></div></div><div className="hero-meta"><span>Seg — Sáb · 08:00 — 18:00</span><span>Rua Luiz Vaz de Camões, 305 · Taubaté/SP</span></div></section>
      <section className="visual-proof section-pad"><div className="section-kicker">01 / O cuidado aparece</div><div className="visual-proof-grid"><div><Image src="/images/green-wash-team.png" alt="Equipe Green Wash trabalhando no cuidado automotivo" width={1200} height={1500} sizes="(max-width: 760px) 100vw, 58vw" /></div><div className="visual-proof-copy"><p className="proof-label">Material confirmado</p><h2>Cuidado técnico,<br /><span>visível nos detalhes.</span></h2><p>A imagem mostra a equipe Green Wash em atendimento. Para agilizar a avaliação do seu carro, envie também 2 ou 3 fotos pelo WhatsApp.</p><a className="text-link" href="#orcamento">Começar orçamento <Arrow /></a></div></div></section>
      <section className="intro section-pad"><div className="section-kicker">02 / O cuidado certo</div><div className="intro-grid"><h2>Um carro bem cuidado<br /><span>muda o dia.</span></h2><p>Do interior à pintura, cada serviço é feito com técnica e produtos biodegradáveis. Comece seu orçamento em poucos passos — sem formulário, sem perguntas repetidas.</p></div></section>
      <section className="services section-pad" id="servicos"><div className="section-kicker">03 / Serviços</div><div className="section-heading"><h2>Para cada detalhe,<br /><span>um jeito de cuidar.</span></h2><p>Escolha o que seu carro precisa. A Green Wash entende o restante.</p></div><div className="service-list">{services.map((s, i) => <div className="service-row" key={s}><span className="service-no">0{i + 1}</span><h3>{s}</h3><span className="service-arrow">↗</span></div>)}</div></section>
      <section className="quote-section" id="orcamento"><div className="quote-intro"><div className="section-kicker">04 / Orçamento guiado</div><h2>Chegue ao orçamento<br /><em>sem começar do zero.</em></h2><p>Você informa o que precisa uma vez. A mensagem chega pronta no WhatsApp da Green Wash.</p><div className="quote-note"><span className="green-dot" /> Leva menos de 30 segundos</div></div><div className="wizard" aria-live="polite"><div className="wizard-top"><span>ORÇAMENTO RÁPIDO</span><span>{step < 5 ? `0${step} / 04` : 'RESUMO'}</span></div>{step < 5 && <div className="progress"><span style={{ width: `${step * 25}%` }} /></div>}
        {step === 1 && <div className="wizard-step"><p className="step-label">PASSO 01</p><h3>Qual serviço você procura?</h3><div className="choice-grid">{services.map((s) => <button className="choice" key={s} onClick={() => choose('service', s, 2)}>{s}<span>↗</span></button>)}</div></div>}
        {step === 2 && <div className="wizard-step"><button className="back" onClick={() => setStep(1)}>← Voltar</button><p className="step-label">PASSO 02</p><h3>Qual o veículo?</h3><div className="choice-grid compact">{['Hatch', 'Sedan', 'SUV', 'Picape', 'Moto', 'Outro'].map((s) => <button className={quote.category === s ? 'choice selected' : 'choice'} key={s} onClick={() => choose('category', s)}>{s}<span>{quote.category === s ? '✓' : '↗'}</span></button>)}</div>{quote.category && <div className="model-area"><label htmlFor="model">Marca e modelo <small>opcional</small></label><input id="model" value={quote.model} onChange={(e) => setQuote({ ...quote, model: e.target.value })} placeholder="Ex.: Honda Civic" /><button className="quick-choice" onClick={() => { setQuote({ ...quote, model: 'Honda Civic' }); setStep(3) }}>Honda Civic <span>↗</span></button></div>}</div>}
        {step === 3 && <div className="wizard-step"><button className="back" onClick={() => setStep(2)}>← Voltar</button><p className="step-label">PASSO 03</p><h3>O que melhor descreve a situação?</h3><div className="choice-grid">{situations.map((s) => <button className="choice" key={s} onClick={() => choose('situation', s, 4)}>{s}<span>↗</span></button>)}</div></div>}
        {step === 4 && <div className="wizard-step"><button className="back" onClick={() => setStep(3)}>← Voltar</button><p className="step-label">PASSO 04</p><h3>Quando pretende fazer?</h3><div className="choice-grid">{timings.map((s) => <button className="choice" key={s} onClick={() => choose('timing', s, 5)}>{s}<span>↗</span></button>)}</div></div>}
        {step === 5 && <div className="wizard-step summary"><button className="back" onClick={() => setStep(4)}>← Voltar</button><p className="step-label">SEU RESUMO</p><h3>Pronto para conversar.</h3><div className="summary-list"><div><span>Serviço</span><strong>{quote.service}</strong></div><div><span>Veículo</span><strong>{quote.category}</strong></div><div><span>Modelo</span><strong>{quote.model || 'A confirmar'}</strong></div><div><span>Situação</span><strong>{quote.situation}</strong></div><div><span>Quando</span><strong>{quote.timing}</strong></div></div><a className="button button-green whatsapp" href={whatsapp} target="_blank" rel="noopener noreferrer">Continuar no WhatsApp <Arrow /></a><p className="whatsapp-note">Para agilizar a avaliação, envie também 2 ou 3 fotos do veículo pelo WhatsApp.</p><p className="privacy">Você fala direto com a Green Wash. Sem cadastro.</p></div>}
      </div></section>
      <section className="trust section-pad" id="diferenciais"><div className="section-kicker">05 / Por que Green Wash</div><div className="trust-grid"><div><p className="big-number">12<span>+</span></p><p className="big-label">anos no ramo</p></div><div className="trust-copy"><h2>Técnica para cuidar.<br /><span>Tempo para confiar.</span></h2><div className="trust-lines"><p><b>01</b> Produtos biodegradáveis</p><p><b>02</b> Equipe especializada</p><p><b>03</b> Atendimento de segunda a sábado</p></div></div></div></section>
      <section className="location section-pad" id="localizacao"><div><div className="section-kicker">06 / Onde estamos</div><h2>Seu carro, em boas mãos<br /><span>em Taubaté.</span></h2><p>Rua Luiz Vaz de Camões, 305<br />Jardim Ana Rosa · Taubaté/SP</p><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Green+Wash+Est%C3%A9tica+Automotiva+Taubat%C3%A9" target="_blank" rel="noopener noreferrer">Abrir no Maps ↗</a></div><div className="hours"><p>HORÁRIOS</p><div><span>Segunda a sábado</span><strong>08:00 — 18:00</strong></div><div><span>Domingo</span><strong>Fechado</strong></div></div></section>
    </div><footer><div className="brand-word">GREEN<br /><span>WASH</span></div><p>Estética automotiva<br />Taubaté · SP</p><a href={`https://wa.me/${WA}`} target="_blank" rel="noopener noreferrer">WhatsApp ↗</a><small>© Green Wash 2026</small></footer>
  </main>
}