'use client'
import { useState } from 'react'
import Image from 'next/image'
const WA = '5512992028120'
type Step = 1 | 2 | 3 | 4 | 5
type Quote = { service: string; category: string; model: string; situation: string; timing: string }
const services = ['HigienizaÃ§Ã£o interna', 'Lavagem detalhada', 'Polimento & cristalizaÃ§Ã£o', 'ProteÃ§Ã£o cerÃ¢mica', 'FarÃ³is', 'Ar-condicionado']
const situations = ['Manchas / sujeira', 'ManutenÃ§Ã£o periÃ³dica', 'Odor', 'Pelos de animais', 'Sujeira intensa']
const timings = ['Hoje / assim que possÃ­vel', 'Esta semana', 'Nos prÃ³ximos dias', 'SÃ³ estou pesquisando']
function Arrow() { return <span aria-hidden="true">â†—</span> }
export default function Home() {
  const [step, setStep] = useState<Step>(1); const [quote, setQuote] = useState<Quote>({ service: '', category: '', model: '', situation: '', timing: '' }); const [menu, setMenu] = useState(false)
  const startQuote = () => { document.getElementById('orcamento')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); setStep(1) }
  const choose = (key: keyof Quote, value: string, next?: Step) => { setQuote((q) => ({ ...q, [key]: value })); if (next) setStep(next) }
  const message = `OlÃ¡! Vim pelo orÃ§amento online da Green Wash.\n\nServiÃ§o: ${quote.service}\nVeÃ­culo: ${quote.model || 'A confirmar'}\nCategoria: ${quote.category}\nSituaÃ§Ã£o: ${quote.situation}\nQuando pretendo fazer: ${quote.timing}\n\nGostaria de saber valor e disponibilidade.`
  const whatsapp = `https://wa.me/${WA}?text=${encodeURIComponent(message)}`
  return <main><a className="skip" href="#conteudo">Pular para o conteÃºdo</a>
    <header className="site-header"><a className="brand" href="#top" aria-label="Green Wash, inÃ­cio"><Image src="/projects/green-wash/brand/green-wash-logo.png" alt="Green Wash" width={270} height={96} /></a><nav className={menu ? 'nav open' : 'nav'} aria-label="NavegaÃ§Ã£o principal"><a href="#servicos" onClick={() => setMenu(false)}>ServiÃ§os</a><a href="#diferenciais" onClick={() => setMenu(false)}>Por que Green Wash</a><a href="#orcamento" onClick={() => setMenu(false)}>OrÃ§amento</a><a href="#localizacao" onClick={() => setMenu(false)}>LocalizaÃ§Ã£o</a></nav><button className="header-cta" onClick={startQuote}>Pedir orÃ§amento <Arrow /></button><button className="menu-button" aria-label={menu ? 'Fechar menu' : 'Abrir menu'} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? 'Ã—' : 'Menu'}</button></header>
    <div id="conteudo"><section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><i /> EstÃ©tica automotiva Â· TaubatÃ©/SP</p><h1>Cuidado que<br /><em>aparece</em> nos detalhes.</h1><p className="hero-text">HigienizaÃ§Ã£o, proteÃ§Ã£o e acabamento para o carro voltar a parecer cuidado.</p><div className="hero-actions"><button className="button button-green" onClick={startQuote}>Montar meu orÃ§amento <Arrow /></button><a className="text-link" href="#servicos">Ver serviÃ§os <span>â†“</span></a></div></div><div className="hero-media"><Image src="/images/green-wash-team.png" alt="Equipe Green Wash realizando higienizaÃ§Ã£o automotiva" width={1200} height={1500} priority sizes="(max-width: 760px) 100vw, 45vw" /><div className="hero-caption"><span>Green Wash</span><span>12+ anos no ramo</span></div></div><div className="hero-meta"><span>01 â€” 02</span><span>TaubatÃ© Â· SP</span></div></section>
      <section className="intro section-pad"><div className="section-kicker">01 / O cuidado certo</div><div className="intro-grid"><h2>Um carro bem cuidado<br /><span>muda o dia.</span></h2><p>Do interior Ã  pintura, cada serviÃ§o Ã© feito com tÃ©cnica e produtos biodegradÃ¡veis. Comece seu orÃ§amento em poucos passos â€” sem formulÃ¡rio, sem perguntas repetidas.</p></div></section>
      <section className="services section-pad" id="servicos"><div className="section-kicker">02 / ServiÃ§os</div><div className="section-heading"><h2>Para cada detalhe,<br /><span>um jeito de cuidar.</span></h2><p>Escolha o que seu carro precisa. A Green Wash entende o restante.</p></div><div className="service-list">{['Lavagem detalhada','HigienizaÃ§Ã£o interna','Polimento & cristalizaÃ§Ã£o','ProteÃ§Ã£o cerÃ¢mica','Ar-condicionado','FarÃ³is'].map((s, i) => <div className="service-row" key={s}><span className="service-no">0{i + 1}</span><h3>{s}</h3><span className="service-arrow">â†—</span></div>)}</div></section>
      <section className="quote-section" id="orcamento"><div className="quote-intro"><div className="section-kicker">03 / OrÃ§amento guiado</div><h2>Chegue ao orÃ§amento<br /><em>sem comeÃ§ar do zero.</em></h2><p>Conte rapidamente o que seu carro precisa. A mensagem chega pronta no WhatsApp da Green Wash.</p><div className="quote-note"><span className="green-dot" /> Leva menos de 30 segundos</div></div><div className="wizard" aria-live="polite"><div className="wizard-top"><span>ORÃ‡AMENTO RÃPIDO</span><span>{step < 5 ? `0${step} / 04` : 'RESUMO'}</span></div>{step < 5 && <div className="progress"><span style={{ width: `${step * 25}%` }} /></div>}
        {step === 1 && <div className="wizard-step"><p className="step-label">PASSO 01</p><h3>O que seu carro precisa?</h3><div className="choice-grid">{services.map((s) => <button className="choice" key={s} onClick={() => choose('service', s, 2)}>{s}<span>â†—</span></button>)}</div></div>}
        {step === 2 && <div className="wizard-step"><button className="back" onClick={() => setStep(1)}>â† Voltar</button><p className="step-label">PASSO 02</p><h3>Qual Ã© o seu veÃ­culo?</h3><div className="choice-grid compact">{['Hatch','Sedan','SUV','Picape','Outro'].map((s) => <button className={quote.category === s ? 'choice selected' : 'choice'} key={s} onClick={() => choose('category', s)}>{s}<span>{quote.category === s ? 'âœ“' : 'â†—'}</span></button>)}</div>{quote.category && <div className="model-area"><label htmlFor="model">Marca e modelo <small>opcional</small></label><input id="model" value={quote.model} onChange={(e) => setQuote({ ...quote, model: e.target.value })} placeholder="Ex.: Honda Civic" /><button className="quick-choice" onClick={() => { setQuote({ ...quote, model: 'Honda Civic' }); setStep(3) }}>Honda Civic <span>â†—</span></button></div>}</div>}
        {step === 3 && <div className="wizard-step"><button className="back" onClick={() => setStep(2)}>â† Voltar</button><p className="step-label">PASSO 03</p><h3>Como estÃ¡ o interior?</h3><div className="choice-grid">{situations.map((s) => <button className="choice" key={s} onClick={() => choose('situation', s, 4)}>{s}<span>â†—</span></button>)}</div></div>}
        {step === 4 && <div className="wizard-step"><button className="back" onClick={() => setStep(3)}>â† Voltar</button><p className="step-label">PASSO 04</p><h3>Quando pretende fazer?</h3><div className="choice-grid">{timings.map((s) => <button className="choice" key={s} onClick={() => choose('timing', s, 5)}>{s}<span>â†—</span></button>)}</div></div>}
        {step === 5 && <div className="wizard-step summary"><button className="back" onClick={() => setStep(4)}>â† Voltar</button><p className="step-label">SEU RESUMO</p><h3>Pronto para conversar.</h3><div className="summary-list"><div><span>ServiÃ§o</span><strong>{quote.service}</strong></div><div><span>VeÃ­culo</span><strong>{quote.model || 'A confirmar'} <small>Â· {quote.category}</small></strong></div><div><span>SituaÃ§Ã£o</span><strong>{quote.situation}</strong></div><div><span>Quando</span><strong>{quote.timing}</strong></div></div><a className="button button-green whatsapp" href={whatsapp} target="_blank" rel="noopener noreferrer">Continuar no WhatsApp <Arrow /></a><p className="privacy">VocÃª fala direto com a Green Wash. Sem cadastro.</p></div>}
      </div></section>
      <section className="trust section-pad" id="diferenciais"><div className="section-kicker">04 / Por que Green Wash</div><div className="trust-grid"><div><p className="big-number">12<span>+</span></p><p className="big-label">anos no ramo</p></div><div className="trust-copy"><h2>TÃ©cnica para cuidar.<br /><span>Tempo para confiar.</span></h2><div className="trust-lines"><p><b>01</b> Produtos biodegradÃ¡veis</p><p><b>02</b> Equipe especializada</p><p><b>03</b> Atendimento de segunda a sÃ¡bado</p></div></div></div></section>
      <section className="location section-pad" id="localizacao"><div><div className="section-kicker">05 / Onde estamos</div><h2>Seu carro, em boas mÃ£os<br /><span>em TaubatÃ©.</span></h2><p>Rua Luiz Vaz de CamÃµes, 305<br />Jardim Ana Rosa Â· TaubatÃ©/SP</p><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Green+Wash+Est%C3%A9tica+Automotiva+Taubat%C3%A9" target="_blank" rel="noopener noreferrer">Abrir no Maps â†—</a></div><div className="hours"><p>HORÃRIOS</p><div><span>Segunda a sÃ¡bado</span><strong>08:00 â€” 18:00</strong></div><div><span>Domingo</span><strong>Fechado</strong></div></div></section></div><footer><div className="brand-word">GREEN<br /><span>WASH</span></div><p>EstÃ©tica automotiva<br />TaubatÃ© Â· SP</p><a href={`https://wa.me/${WA}`} target="_blank" rel="noopener noreferrer">WhatsApp â†—</a><small>Â© Green Wash 2026</small></footer>
  </main>
}

